"""Repository protocol definitions.

Abstract interfaces for all DB access. Concrete implementations
(SQLite, PostgreSQL) must satisfy these protocols.
"""
from __future__ import annotations

from typing import Protocol, runtime_checkable, Any


# ── Session Repository ──────────────────────────────────────────────

@runtime_checkable
class SessionRepository(Protocol):
    async def upsert(self, session_data: dict, project_id: str) -> None: ...
    async def get_by_id(self, session_id: str) -> dict | None: ...
    async def list_paginated(
        self, offset: int, limit: int, project_id: str | None = None,
        sort_by: str = "started_at", sort_order: str = "desc", filters: dict | None = None,
    ) -> list[dict]: ...
    async def count(self, project_id: str | None = None, filters: dict | None = None) -> int: ...
    async def delete_by_source(self, source_file: str) -> None: ...

    # Detail tables
    async def upsert_logs(self, session_id: str, logs: list[dict]) -> None: ...
    async def upsert_tool_usage(self, session_id: str, tools: list[dict]) -> None: ...
    async def upsert_file_updates(self, session_id: str, updates: list[dict]) -> None: ...
    async def upsert_artifacts(self, session_id: str, artifacts: list[dict]) -> None: ...
    async def get_logs(self, session_id: str) -> list[dict]: ...
    async def get_tool_usage(self, session_id: str) -> list[dict]: ...
    async def get_file_updates(self, session_id: str) -> list[dict]: ...
    async def get_artifacts(self, session_id: str) -> list[dict]: ...


# ── Document Repository ─────────────────────────────────────────────

@runtime_checkable
class DocumentRepository(Protocol):
    async def upsert(self, doc_data: dict, project_id: str) -> None: ...
    async def get_by_id(self, doc_id: str) -> dict | None: ...
    async def get_by_path(self, project_id: str, canonical_path: str) -> dict | None: ...
    async def list_paginated(
        self, project_id: str, offset: int, limit: int, filters: dict | None = None,
    ) -> list[dict]: ...
    async def count(self, project_id: str, filters: dict | None = None) -> int: ...
    async def list_all(self, project_id: str | None = None) -> list[dict]: ...
    async def get_catalog_facets(self, project_id: str, filters: dict | None = None) -> dict: ...
    async def delete_by_source(self, source_file: str) -> None: ...


# ── Task Repository ─────────────────────────────────────────────────

@runtime_checkable
class TaskRepository(Protocol):
    async def upsert(self, task_data: dict, project_id: str) -> None: ...
    async def get_by_id(self, task_id: str) -> dict | None: ...
    async def list_all(self, project_id: str | None = None) -> list[dict]: ...
    async def list_by_feature(self, feature_id: str, phase_id: str | None = None) -> list[dict]: ...
    async def delete_by_source(self, source_file: str) -> None: ...


# ── Feature Repository ──────────────────────────────────────────────

@runtime_checkable
class FeatureRepository(Protocol):
    async def upsert(self, feature_data: dict, project_id: str) -> None: ...
    async def get_by_id(self, feature_id: str) -> dict | None: ...
    async def list_all(self, project_id: str | None = None) -> list[dict]: ...
    async def upsert_phases(self, feature_id: str, phases: list[dict]) -> None: ...
    async def get_phases(self, feature_id: str) -> list[dict]: ...
    async def delete(self, feature_id: str) -> None: ...


# ── Entity Links Repository ─────────────────────────────────────────

@runtime_checkable
class EntityLinkRepository(Protocol):
    async def upsert(self, link_data: dict) -> int: ...
    async def get_links_for(
        self, entity_type: str, entity_id: str, link_type: str | None = None,
    ) -> list[dict]: ...
    async def get_tree(self, entity_type: str, entity_id: str) -> dict: ...
    async def delete_auto_links(self, source_type: str, source_id: str) -> None: ...
    async def delete_all_for(self, entity_type: str, entity_id: str) -> None: ...


# ── Tags Repository ─────────────────────────────────────────────────

@runtime_checkable
class TagRepository(Protocol):
    async def get_or_create(self, name: str, color: str = "") -> int: ...
    async def tag_entity(self, entity_type: str, entity_id: str, tag_id: int) -> None: ...
    async def untag_entity(self, entity_type: str, entity_id: str, tag_id: int) -> None: ...
    async def get_tags_for(self, entity_type: str, entity_id: str) -> list[dict]: ...
    async def get_entities_for_tag(self, tag_id: int) -> list[dict]: ...
    async def list_all(self) -> list[dict]: ...


# ── Sync State Repository ───────────────────────────────────────────

@runtime_checkable
class SyncStateRepository(Protocol):
    async def get_sync_state(self, file_path: str) -> dict | None: ...
    async def upsert_sync_state(self, state: dict) -> None: ...
    async def delete_sync_state(self, file_path: str) -> None: ...
    async def list_all(self, project_id: str | None = None) -> list[dict]: ...


# ── Alert Config Repository ─────────────────────────────────────────

@runtime_checkable
class AlertConfigRepository(Protocol):
    async def list_all(self, project_id: str | None = None) -> list[dict]: ...
    async def upsert(self, config_data: dict) -> None: ...
    async def delete(self, config_id: str) -> None: ...


# ── Analytics Repository ────────────────────────────────────────────

@runtime_checkable
class AnalyticsRepository(Protocol):
    async def insert_entry(self, entry: dict) -> int: ...
    async def link_to_entity(self, analytics_id: int, entity_type: str, entity_id: str) -> None: ...
    async def get_trends(
        self, project_id: str, metric_type: str, period: str = "daily",
        start: str | None = None, end: str | None = None,
    ) -> list[dict]: ...
    async def get_metric_types(self) -> list[dict]: ...
