"""Repository protocol definitions.

Abstract interfaces for all DB access. Concrete implementations
(SQLite, PostgreSQL) must satisfy these protocols.
"""
from __future__ import annotations

from typing import Protocol, runtime_checkable, Any


# ── Session Repository ──────────────────────────────────────────────

@runtime_checkable
class SessionRepository(Protocol):
    async def upsert(self, session_data: dict, project_id: str) -> None: ...
    async def get_by_id(self, session_id: str) -> dict | None: ...
    async def list_by_source(self, source_file: str) -> list[dict]: ...
    async def list_paginated(
        self, offset: int, limit: int, project_id: str | None = None,
        sort_by: str = "started_at", sort_order: str = "desc", filters: dict | None = None,
    ) -> list[dict]: ...
    async def count(self, project_id: str | None = None, filters: dict | None = None) -> int: ...
    async def get_model_facets(self, project_id: str | None = None, include_subagents: bool = True) -> list[dict]: ...
    async def get_platform_facets(self, project_id: str | None = None, include_subagents: bool = True) -> list[dict]: ...
    async def delete_by_source(self, source_file: str) -> None: ...
    async def update_usage_fields(self, session_id: str, usage_fields: dict[str, int]) -> None: ...
    async def update_observability_fields(self, session_id: str, observability_fields: dict[str, Any]) -> None: ...

    # Detail tables
    async def upsert_logs(self, session_id: str, logs: list[dict]) -> None: ...
    async def upsert_tool_usage(self, session_id: str, tools: list[dict]) -> None: ...
    async def upsert_file_updates(self, session_id: str, updates: list[dict]) -> None: ...
    async def upsert_artifacts(self, session_id: str, artifacts: list[dict]) -> None: ...
    async def get_logs(self, session_id: str) -> list[dict]: ...
    async def get_tool_usage(self, session_id: str) -> list[dict]: ...
    async def get_file_updates(self, session_id: str) -> list[dict]: ...
    async def get_artifacts(self, session_id: str) -> list[dict]: ...
    async def delete_relationships_for_source(self, project_id: str, source_file: str) -> None: ...
    async def upsert_relationships(self, project_id: str, source_file: str, relationships: list[dict]) -> None: ...
    async def list_relationships(self, project_id: str, session_id: str) -> list[dict]: ...


@runtime_checkable
class SessionMessageRepository(Protocol):
    async def replace_session_messages(self, session_id: str, messages: list[dict[str, Any]]) -> None: ...
    async def list_by_session(self, session_id: str) -> list[dict[str, Any]]: ...
    async def search_messages(
        self,
        project_id: str,
        query: str,
        *,
        feature_id: str | None = None,
        conversation_family_id: str | None = None,
        session_id: str | None = None,
        limit: int = 50,
    ) -> list[dict[str, Any]]: ...


@runtime_checkable
class SessionIntelligenceRepository(Protocol):
    async def replace_session_sentiment_facts(self, session_id: str, facts: list[dict[str, Any]]) -> None: ...
    async def list_session_sentiment_facts(self, session_id: str) -> list[dict[str, Any]]: ...
    async def replace_session_code_churn_facts(self, session_id: str, facts: list[dict[str, Any]]) -> None: ...
    async def list_session_code_churn_facts(self, session_id: str) -> list[dict[str, Any]]: ...
    async def replace_session_scope_drift_facts(self, session_id: str, facts: list[dict[str, Any]]) -> None: ...
    async def list_session_scope_drift_facts(self, session_id: str) -> list[dict[str, Any]]: ...
    async def list_backfill_sessions(
        self,
        project_id: str,
        *,
        after_started_at: str = "",
        after_session_id: str = "",
        limit: int = 200,
    ) -> list[dict[str, Any]]: ...
    async def load_backfill_checkpoint(
        self,
        project_id: str,
        *,
        checkpoint_key: str,
    ) -> dict[str, Any]: ...
    async def save_backfill_checkpoint(
        self,
        project_id: str,
        checkpoint: dict[str, Any],
        *,
        checkpoint_key: str,
    ) -> None: ...
    async def delete_backfill_checkpoint(
        self,
        project_id: str,
        *,
        checkpoint_key: str,
    ) -> None: ...


# ── Document Repository ─────────────────────────────────────────────

@runtime_checkable
class DocumentRepository(Protocol):
    async def upsert(self, doc_data: dict, project_id: str) -> None: ...
    async def get_by_id(self, doc_id: str) -> dict | None: ...
    async def get_by_path(self, project_id: str, canonical_path: str) -> dict | None: ...
    async def list_paginated(
        self, project_id: str, offset: int, limit: int, filters: dict | None = None,
    ) -> list[dict]: ...
    async def count(self, project_id: str, filters: dict | None = None) -> int: ...
    async def list_all(self, project_id: str | None = None) -> list[dict]: ...
    async def get_catalog_facets(self, project_id: str, filters: dict | None = None) -> dict: ...
    async def delete_by_source(self, source_file: str) -> None: ...


# ── Task Repository ─────────────────────────────────────────────────

@runtime_checkable
class TaskRepository(Protocol):
    async def upsert(self, task_data: dict, project_id: str) -> None: ...
    async def get_by_id(self, task_id: str) -> dict | None: ...
    async def list_paginated(
        self, project_id: str | None, offset: int, limit: int,
    ) -> list[dict]: ...
    async def count(self, project_id: str | None = None) -> int: ...
    async def list_all(self, project_id: str | None = None) -> list[dict]: ...
    async def list_by_feature(self, feature_id: str, phase_id: str | None = None) -> list[dict]: ...
    async def delete_by_source(self, source_file: str) -> None: ...


# ── Feature Repository ──────────────────────────────────────────────

@runtime_checkable
class FeatureRepository(Protocol):
    async def upsert(self, feature_data: dict, project_id: str) -> None: ...
    async def get_by_id(self, feature_id: str) -> dict | None: ...
    async def list_paginated(
        self, project_id: str | None, offset: int, limit: int,
    ) -> list[dict]: ...
    async def count(self, project_id: str | None = None) -> int: ...
    async def list_all(self, project_id: str | None = None) -> list[dict]: ...
    async def upsert_phases(self, feature_id: str, phases: list[dict]) -> None: ...
    async def get_phases(self, feature_id: str) -> list[dict]: ...
    async def delete(self, feature_id: str) -> None: ...


# ── Entity Links Repository ─────────────────────────────────────────

@runtime_checkable
class EntityLinkRepository(Protocol):
    async def upsert(self, link_data: dict) -> int: ...
    async def get_links_for(
        self, entity_type: str, entity_id: str, link_type: str | None = None,
    ) -> list[dict]: ...
    async def get_tree(self, entity_type: str, entity_id: str) -> dict: ...
    async def delete_link(
        self,
        source_type: str,
        source_id: str,
        target_type: str,
        target_id: str,
        link_type: str = "related",
    ) -> None: ...
    async def delete_auto_links(self, source_type: str, source_id: str) -> None: ...
    async def delete_all_for(self, entity_type: str, entity_id: str) -> None: ...


# ── Tags Repository ─────────────────────────────────────────────────

@runtime_checkable
class TagRepository(Protocol):
    async def get_or_create(self, name: str, color: str = "") -> int: ...
    async def tag_entity(self, entity_type: str, entity_id: str, tag_id: int) -> None: ...
    async def untag_entity(self, entity_type: str, entity_id: str, tag_id: int) -> None: ...
    async def get_tags_for(self, entity_type: str, entity_id: str) -> list[dict]: ...
    async def get_entities_for_tag(self, tag_id: int) -> list[dict]: ...
    async def list_all(self) -> list[dict]: ...


# ── Sync State Repository ───────────────────────────────────────────

@runtime_checkable
class SyncStateRepository(Protocol):
    async def get_sync_state(self, file_path: str) -> dict | None: ...
    async def upsert_sync_state(self, state: dict) -> None: ...
    async def delete_sync_state(self, file_path: str) -> None: ...
    async def list_all(self, project_id: str | None = None) -> list[dict]: ...


# ── Alert Config Repository ─────────────────────────────────────────

@runtime_checkable
class AlertConfigRepository(Protocol):
    async def list_all(self, project_id: str | None = None) -> list[dict]: ...
    async def upsert(self, config_data: dict) -> None: ...
    async def delete(self, config_id: str) -> None: ...


@runtime_checkable
class PricingCatalogRepository(Protocol):
    async def list_entries(self, project_id: str, platform_type: str | None = None) -> list[dict]: ...
    async def get_entry(self, project_id: str, platform_type: str, model_id: str = "") -> dict | None: ...
    async def upsert_entry(self, entry_data: dict[str, Any], project_id: str) -> dict[str, Any]: ...
    async def delete_entry(self, project_id: str, platform_type: str, model_id: str = "") -> None: ...


@runtime_checkable
class TelemetryQueueRepository(Protocol):
    async def enqueue(
        self,
        session_id: str,
        project_slug: str,
        payload: dict[str, Any] | str,
        queue_id: str | None = None,
    ) -> dict[str, Any]: ...
    async def fetch_pending_batch(self, batch_size: int) -> list[dict[str, Any]]: ...
    async def mark_synced(self, queue_id: str) -> dict[str, Any] | None: ...
    async def mark_failed(
        self,
        queue_id: str,
        error: str,
        attempt_count: int | None = None,
    ) -> dict[str, Any] | None: ...
    async def mark_abandoned(
        self,
        queue_id: str,
        error: str,
        attempt_count: int | None = None,
    ) -> dict[str, Any] | None: ...
    async def get_queue_stats(self) -> dict[str, Any]: ...
    async def purge_old_synced(self, retention_days: int) -> int: ...


# ── Analytics Repository ────────────────────────────────────────────

@runtime_checkable
class AnalyticsRepository(Protocol):
    async def insert_entry(self, entry: dict) -> int: ...
    async def link_to_entity(self, analytics_id: int, entity_type: str, entity_id: str) -> None: ...
    async def get_trends(
        self, project_id: str, metric_type: str, period: str = "daily",
        start: str | None = None, end: str | None = None,
    ) -> list[dict]: ...
    async def get_metric_types(self) -> list[dict]: ...


@runtime_checkable
class SessionUsageRepository(Protocol):
    async def replace_session_usage(
        self,
        project_id: str,
        session_id: str,
        events: list[dict[str, Any]],
        attributions: list[dict[str, Any]],
    ) -> None: ...
    async def get_session_usage_events(self, session_id: str) -> list[dict[str, Any]]: ...
    async def get_session_usage_attributions(self, session_id: str) -> list[dict[str, Any]]: ...
    async def count_usage_events(self, project_id: str) -> int: ...


@runtime_checkable
class AgenticIntelligenceRepository(Protocol):
    async def upsert_definition_source(self, source_data: dict, project_id: str | None = None) -> dict: ...
    async def get_definition_source(self, project_id: str, source_kind: str = "skillmeat") -> dict | None: ...
    async def update_definition_source_status(
        self,
        project_id: str,
        source_kind: str,
        *,
        last_synced_at: str = "",
        last_sync_status: str = "",
        last_sync_error: str = "",
    ) -> dict | None: ...
    async def upsert_external_definition(self, definition_data: dict, project_id: str | None = None) -> dict: ...
    async def list_external_definitions(
        self,
        project_id: str,
        *,
        definition_type: str | None = None,
        limit: int = 500,
        offset: int = 0,
    ) -> list[dict]: ...
    async def get_external_definition(self, project_id: str, definition_type: str, external_id: str) -> dict | None: ...
    async def upsert_stack_observation(
        self,
        observation_data: dict,
        components: list[dict] | None = None,
        project_id: str | None = None,
    ) -> dict: ...
    async def get_stack_observation(self, project_id: str, session_id: str) -> dict | None: ...
    async def list_stack_observations(
        self,
        project_id: str,
        *,
        limit: int = 200,
        offset: int = 0,
        feature_id: str | None = None,
    ) -> list[dict]: ...
    async def list_stack_components(self, observation_id: int) -> list[dict]: ...
    async def upsert_effectiveness_rollup(
        self,
        rollup_data: dict,
        project_id: str | None = None,
    ) -> dict: ...
    async def list_effectiveness_rollups(
        self,
        project_id: str,
        *,
        scope_type: str | None = None,
        scope_id: str | None = None,
        period: str | None = None,
        limit: int = 200,
        offset: int = 0,
    ) -> list[dict]: ...
    async def purge_effectiveness_rollups(
        self,
        project_id: str,
        *,
        period: str | None = None,
    ) -> None: ...
    async def upsert_session_memory_draft(
        self,
        draft_data: dict[str, Any],
        project_id: str | None = None,
    ) -> dict[str, Any]: ...
    async def get_session_memory_draft(self, project_id: str, draft_id: int) -> dict[str, Any] | None: ...
    async def count_session_memory_drafts(
        self,
        project_id: str,
        *,
        session_id: str | None = None,
        status: str | None = None,
    ) -> int: ...
    async def list_session_memory_drafts(
        self,
        project_id: str,
        *,
        session_id: str | None = None,
        status: str | None = None,
        limit: int = 100,
        offset: int = 0,
    ) -> list[dict[str, Any]]: ...
    async def review_session_memory_draft(
        self,
        project_id: str,
        draft_id: int,
        *,
        decision: str,
        actor: str = "",
        notes: str = "",
    ) -> dict[str, Any] | None: ...
    async def record_session_memory_draft_publish_attempt(
        self,
        project_id: str,
        draft_id: int,
        *,
        actor: str = "",
        notes: str = "",
        module_id: str = "",
        memory_id: str = "",
        source_url: str = "",
        error: str = "",
    ) -> dict[str, Any] | None: ...


# ── Test Visualizer Repositories ───────────────────────────────────

@runtime_checkable
class TestRunRepository(Protocol):
    async def upsert(self, run_data: dict, project_id: str | None = None) -> None: ...
    async def get_by_id(self, run_id: str) -> dict | None: ...
    async def list_paginated(self, offset: int, limit: int, project_id: str | None = None) -> list[dict]: ...
    async def delete_by_source(self, source_file: str) -> None: ...
    async def list_by_project(self, project_id: str, limit: int = 100, offset: int = 0) -> list[dict]: ...
    async def list_by_session(
        self, project_id: str, agent_session_id: str, limit: int = 100, offset: int = 0
    ) -> list[dict]: ...
    async def list_filtered(
        self,
        project_id: str,
        *,
        agent_session_id: str | None = None,
        feature_id: str | None = None,
        domain_id: str | None = None,
        git_sha: str | None = None,
        since: str | None = None,
        limit: int = 100,
        offset: int = 0,
    ) -> tuple[list[dict], int]: ...
    async def get_latest_for_feature(self, project_id: str, feature_id: str) -> dict | None: ...


@runtime_checkable
class TestDefinitionRepository(Protocol):
    async def upsert(self, definition_data: dict, project_id: str | None = None) -> None: ...
    async def get_by_id(self, test_id: str) -> dict | None: ...
    async def list_paginated(self, offset: int, limit: int, project_id: str | None = None) -> list[dict]: ...
    async def delete_by_source(self, source_file: str) -> None: ...
    async def list_by_project(self, project_id: str, limit: int = 100, offset: int = 0) -> list[dict]: ...
    async def get_or_create(
        self,
        project_id: str,
        path: str,
        name: str,
        framework: str = "pytest",
        tags: list[str] | None = None,
        owner: str = "",
    ) -> dict: ...


@runtime_checkable
class TestResultRepository(Protocol):
    async def upsert(self, result_data: dict) -> None: ...
    async def get_by_id(self, run_id: str, test_id: str) -> dict | None: ...
    async def list_paginated(self, offset: int, limit: int, project_id: str | None = None) -> list[dict]: ...
    async def delete_by_source(self, source_file: str) -> None: ...
    async def get_by_run(self, run_id: str) -> list[dict]: ...
    async def list_by_run_filtered(
        self,
        run_id: str,
        *,
        domain_id: str | None = None,
        statuses: list[str] | None = None,
        query: str | None = None,
        sort_by: str = "status",
        sort_order: str = "asc",
        limit: int = 100,
        offset: int = 0,
    ) -> tuple[list[dict], int]: ...
    async def get_history_for_test(self, test_id: str, limit: int = 200) -> list[dict]: ...
    async def list_history_for_test(
        self,
        *,
        project_id: str,
        test_id: str,
        since: str | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> tuple[list[dict], int]: ...
    async def list_latest_by_project(
        self,
        *,
        project_id: str,
        since: str | None = None,
    ) -> list[dict]: ...
    async def get_latest_status(self, test_id: str) -> dict | None: ...


@runtime_checkable
class TestDomainRepository(Protocol):
    async def upsert(self, domain_data: dict, project_id: str | None = None) -> None: ...
    async def get_by_id(self, domain_id: str) -> dict | None: ...
    async def list_paginated(self, offset: int, limit: int, project_id: str | None = None) -> list[dict]: ...
    async def delete_by_source(self, source_file: str) -> None: ...
    async def list_tree(self, project_id: str) -> list[dict]: ...
    async def get_or_create_by_name(
        self,
        project_id: str,
        name: str,
        parent_id: str | None = None,
        tier: str = "core",
        description: str = "",
    ) -> dict: ...


@runtime_checkable
class TestMappingRepository(Protocol):
    async def upsert(self, mapping_data: dict, project_id: str | None = None) -> int: ...
    async def get_by_id(self, mapping_id: int) -> dict | None: ...
    async def list_paginated(self, offset: int, limit: int, project_id: str | None = None) -> list[dict]: ...
    async def delete_by_source(self, source_file: str) -> None: ...
    async def list_by_test(self, project_id: str, test_id: str) -> list[dict]: ...
    async def list_by_feature(self, project_id: str, feature_id: str, is_primary_only: bool = False) -> list[dict]: ...
    async def list_by_domain(self, project_id: str, domain_id: str) -> list[dict]: ...
    async def get_primary_for_test(self, project_id: str, test_id: str) -> list[dict]: ...
    async def list_primary_by_tests(self, project_id: str, test_ids: list[str]) -> dict[str, dict]: ...
    async def list_primary_by_project(self, project_id: str, domain_id: str | None = None) -> list[dict]: ...
    async def list_primary_for_run(self, project_id: str, run_id: str) -> list[dict]: ...


@runtime_checkable
class TestIntegrityRepository(Protocol):
    async def upsert(self, signal_data: dict, project_id: str | None = None) -> None: ...
    async def get_by_id(self, signal_id: str) -> dict | None: ...
    async def list_paginated(self, offset: int, limit: int, project_id: str | None = None) -> list[dict]: ...
    async def delete_by_source(self, source_file: str) -> None: ...
    async def list_by_project(self, project_id: str, limit: int = 100, offset: int = 0) -> list[dict]: ...
    async def list_by_sha(self, project_id: str, git_sha: str, limit: int = 100) -> list[dict]: ...
    async def list_since(self, project_id: str, since: str, limit: int = 100) -> list[dict]: ...
    async def list_filtered(
        self,
        *,
        project_id: str,
        since: str | None = None,
        signal_type: str | None = None,
        severity: str | None = None,
        agent_session_id: str | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> tuple[list[dict], int]: ...


# ── Execution Workbench Repository ────────────────────────────────

@runtime_checkable
class ExecutionRepository(Protocol):
    async def create_run(self, run_data: dict) -> dict: ...
    async def update_run(self, run_id: str, updates: dict) -> dict | None: ...
    async def get_run(self, run_id: str) -> dict | None: ...
    async def list_runs(
        self,
        project_id: str,
        *,
        feature_id: str | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> list[dict]: ...
    async def append_run_events(self, run_id: str, events: list[dict]) -> list[dict]: ...
    async def list_events_after_sequence(
        self,
        run_id: str,
        *,
        after_sequence: int = 0,
        limit: int = 200,
    ) -> list[dict]: ...
    async def create_approval(self, approval_data: dict) -> dict: ...
    async def get_pending_approval(self, run_id: str) -> dict | None: ...
    async def resolve_approval(
        self,
        run_id: str,
        *,
        decision: str,
        reason: str = "",
        resolved_by: str = "",
    ) -> dict | None: ...
