#!/usr/bin/env python3
"""Prepare a container-visible CCDash project registry entry.

This helper updates a projects.json file and optionally writes a watcher env
overlay. It intentionally avoids starting containers: watcher binding is a
deployment concern controlled by compose env.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


def _default_project_id(name: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return slug or "ccdash-project"


def _read_registry(path: Path) -> dict[str, Any]:
    if not path.exists() or not path.read_text(encoding="utf-8").strip():
        return {"activeProjectId": None, "projects": []}
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a JSON object")
    projects = data.get("projects")
    if not isinstance(projects, list):
        data["projects"] = []
    return data


def _path_reference(
    *,
    field: str,
    source_kind: str,
    display_value: str,
    filesystem_path: str = "",
    relative_path: str = "",
) -> dict[str, Any]:
    return {
        "field": field,
        "sourceKind": source_kind,
        "displayValue": display_value,
        "filesystemPath": filesystem_path,
        "relativePath": relative_path,
        "repoRef": None,
    }


def _build_project(args: argparse.Namespace) -> dict[str, Any]:
    project_id = args.project_id or _default_project_id(args.name)
    root_path = str(args.root_container).strip()
    sessions_path = str(args.sessions_container).strip() if args.sessions_container else ""
    plan_docs = args.plan_docs.strip() or "docs/project_plans/"
    progress = args.progress.strip() or "progress"
    return {
        "id": project_id,
        "name": args.name,
        "path": root_path,
        "description": args.description or "",
        "repoUrl": args.repo_url or "",
        "agentPlatforms": args.agent_platforms,
        "planDocsPath": plan_docs,
        "sessionsPath": sessions_path,
        "progressPath": progress,
        "pathConfig": {
            "root": _path_reference(
                field="root",
                source_kind="filesystem",
                display_value=root_path,
                filesystem_path=root_path,
            ),
            "planDocs": _path_reference(
                field="plan_docs",
                source_kind="project_root",
                display_value=plan_docs,
                relative_path=plan_docs,
            ),
            "sessions": _path_reference(
                field="sessions",
                source_kind="filesystem",
                display_value=sessions_path,
                filesystem_path=sessions_path,
            ),
            "progress": _path_reference(
                field="progress",
                source_kind="project_root",
                display_value=progress,
                relative_path=progress,
            ),
        },
    }


def _upsert_project(registry: dict[str, Any], project: dict[str, Any], *, active: bool) -> None:
    projects = registry.setdefault("projects", [])
    for index, existing in enumerate(projects):
        if isinstance(existing, dict) and existing.get("id") == project["id"]:
            projects[index] = {**existing, **project}
            break
    else:
        projects.append(project)
    if active:
        registry["activeProjectId"] = project["id"]


def _env_line(name: str, value: str | None) -> str | None:
    if value is None or value == "":
        return None
    return f"{name}={value}"


def _build_watcher_env(args: argparse.Namespace, project_id: str) -> str:
    lines = [
        "# Generated by backend/scripts/container_project_onboarding.py.",
        f"CCDASH_WORKER_PROJECT_ID={project_id}",
        f"CCDASH_WORKER_WATCH_PROJECT_ID={project_id}",
        f"CCDASH_WORKER_WATCH_PROBE_PORT={args.watcher_probe_port}",
        "CCDASH_WORKER_STARTUP_SYNC_ENABLED=false",
        "CCDASH_WORKER_WATCH_STARTUP_SYNC_ENABLED=true",
        "CCDASH_WORKER_WATCH_FILESYSTEM_INGESTION_ENABLED=true",
        "CCDASH_INFERRED_STATUS_WRITEBACK_ENABLED=false",
        "GIT_OPTIONAL_LOCKS=0",
        "CCDASH_STARTUP_SYNC_LIGHT_MODE=true",
        _env_line("CCDASH_PROJECTS_FILE", args.projects_file_for_env),
        _env_line("CCDASH_WORKSPACE_HOST_ROOT", args.workspace_host_root),
        _env_line("CCDASH_WORKSPACE_CONTAINER_ROOT", args.workspace_container_root),
        _env_line("CCDASH_CLAUDE_HOME", args.claude_home),
        _env_line("CCDASH_CLAUDE_CONTAINER_HOME", args.claude_container_home),
        _env_line("CCDASH_CODEX_HOME", args.codex_home),
        _env_line("CCDASH_CODEX_CONTAINER_HOME", args.codex_container_home),
    ]
    return "\n".join(line for line in lines if line) + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create or update a CCDash projects.json entry for container deployment.",
    )
    parser.add_argument("--projects-file", default="projects.json", help="Path to the projects.json registry to update.")
    parser.add_argument("--project-id", help="Stable project id. Defaults to a slug from --name.")
    parser.add_argument("--name", required=True, help="Project display name.")
    parser.add_argument("--description", default="", help="Project description.")
    parser.add_argument("--repo-url", default="", help="Optional repository URL.")
    parser.add_argument("--root-container", required=True, help="Project root path as seen inside containers.")
    parser.add_argument("--plan-docs", default="docs/project_plans/", help="Plan docs path relative to the project root.")
    parser.add_argument("--sessions-container", default="", help="Session JSONL directory as seen inside containers.")
    parser.add_argument("--progress", default="progress", help="Progress path relative to the project root.")
    parser.add_argument(
        "--agent-platform",
        action="append",
        dest="agent_platforms",
        default=None,
        help="Agent platform label. Repeatable. Defaults to Claude Code.",
    )
    parser.add_argument("--no-active", action="store_true", help="Do not set this project as activeProjectId.")
    parser.add_argument("--watcher-env", help="Optional path to write a per-watcher env overlay.")
    parser.add_argument("--watcher-probe-port", default="9466", help="Host/container probe port for this watcher overlay.")
    parser.add_argument(
        "--projects-file-for-env",
        default="../../projects.json",
        help="Value to place in CCDASH_PROJECTS_FILE when writing --watcher-env.",
    )
    parser.add_argument("--workspace-host-root", help="Optional CCDASH_WORKSPACE_HOST_ROOT value for --watcher-env.")
    parser.add_argument("--workspace-container-root", help="Optional CCDASH_WORKSPACE_CONTAINER_ROOT value for --watcher-env.")
    parser.add_argument("--claude-home", help="Optional CCDASH_CLAUDE_HOME value for --watcher-env.")
    parser.add_argument("--claude-container-home", help="Optional CCDASH_CLAUDE_CONTAINER_HOME value for --watcher-env.")
    parser.add_argument("--codex-home", help="Optional CCDASH_CODEX_HOME value for --watcher-env.")
    parser.add_argument("--codex-container-home", help="Optional CCDASH_CODEX_CONTAINER_HOME value for --watcher-env.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.agent_platforms is None:
        args.agent_platforms = ["Claude Code"]

    projects_file = Path(args.projects_file).expanduser()
    registry = _read_registry(projects_file)
    project = _build_project(args)
    _upsert_project(registry, project, active=not args.no_active)

    projects_file.parent.mkdir(parents=True, exist_ok=True)
    projects_file.write_text(json.dumps(registry, indent=2) + "\n", encoding="utf-8")
    print(f"Updated {projects_file} with project {project['id']}")

    if args.watcher_env:
        watcher_env = Path(args.watcher_env).expanduser()
        watcher_env.parent.mkdir(parents=True, exist_ok=True)
        watcher_env.write_text(_build_watcher_env(args, project["id"]), encoding="utf-8")
        print(f"Wrote watcher env overlay {watcher_env}")
    else:
        print(_build_watcher_env(args, project["id"]))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
