"""Transport-neutral agent query service contracts and helpers."""

from backend.application.services.agent_queries import cache
from backend.application.services.agent_queries.cache import (
    _query_cache,
    aclear_project_cache,
    cache_get,
    cache_set,
    clear_cache,
    clear_project_cache,
    compute_cache_key,
    get_cache,
    get_data_version_fingerprint,
    init_postgres_cache_backend,
)
from backend.application.services.agent_queries._filters import (
    AgentQueryProjectScope,
    collect_source_refs,
    derive_data_freshness,
    normalize_entity_ids,
    resolve_project_scope,
    resolve_time_window,
)
from backend.application.services.agent_queries.models import (
    AARReportDTO,
    AARReviewDTO,
    AARReviewFlag,
    AgentQueryEnvelope,
    AnalyticsKPIsDTO,
    AnalyticsOverviewBundleDTO,
    AnalyticsTopModelDTO,
    Bottleneck,
    CostSummary,
    DashboardBundleDTO,
    DocumentRef,
    FeatureEvidenceSummary,
    FeatureForensicsDTO,
    FeaturePlanningContextDTO,
    FeatureSummaryItem,
    KeyMetrics,
    NextRunContextRef,
    OpenQuestionResolutionDTO,
    PhaseContextItem,
    PhaseOperationsDTO,
    PhaseTaskItem,
    PlanningArtifactRef,
    PlanningCommandAlternativeDTO,
    PlanningCommandCapabilityDTO,
    PlanningCommandCenterArtifactDTO,
    PlanningCommandCenterBlockerDTO,
    PlanningCommandCenterCapabilitiesDTO,
    PlanningCommandCenterFeatureDTO,
    PlanningCommandCenterGitStateDTO,
    PlanningCommandCenterItemDTO,
    PlanningCommandCenterLaunchAgentDTO,
    PlanningCommandCenterLaunchBatchDTO,
    PlanningCommandCenterPageDTO,
    PlanningCommandCenterPhaseDTO,
    PlanningCommandCenterPhaseRowDTO,
    PlanningCommandCenterPullRequestDTO,
    PlanningCommandCenterRelatedFileDTO,
    PlanningCommandCenterStatusDTO,
    PlanningCommandCenterStoryPointsDTO,
    PlanningCommandCenterTierDTO,
    PlanningCommandCenterWorktreeDTO,
    PlanningCommandResolutionDTO,
    PlanningCommandRuleId,
    PlanningCommandTargetArtifactDTO,
    PlanningNextRunPreviewDTO,
    PlanningNodeCountsByType,
    PlanningOpenQuestionItem,
    PlanningSpikeItem,
    PlanningViewBundleDTO,
    ProjectPlanningSummaryDTO,
    ProjectPlanningGraphDTO,
    ProjectStatusDTO,
    PromptContextSelection,
    QueryStatus,
    SessionCardDTO,
    SessionRef,
    SessionSummary,
    SnapshotDiagnosticsDTO,
    ArtifactRankingsDTO,
    ArtifactRecommendationsDTO,
    TaskRef,
    TimelineData,
    TokenUsageByModel,
    TurningPoint,
    WorkflowDiagnostic,
    WorkflowDiagnosticsDTO,
    WorkflowObservation,
    WorkflowSummary,
)
from backend.application.services.agent_queries.aar_review import AARReviewQueryService
from backend.application.services.agent_queries.analytics_bundle import AnalyticsBundleQueryService
from backend.application.services.agent_queries.artifact_intelligence import ArtifactIntelligenceQueryService
from backend.application.services.agent_queries.dashboard import DashboardQueryService
from backend.application.services.agent_queries.feature_forensics import FeatureForensicsQueryService
from backend.application.services.agent_queries.feature_evidence_summary import FeatureEvidenceSummaryService
from backend.application.services.agent_queries.live_metrics import LiveActiveCountDTO, LiveMetricsQueryService
from backend.application.services.agent_queries.planning import PlanningQueryService
from backend.application.services.agent_queries.planning_command_center import PlanningCommandCenterQueryService
from backend.application.services.agent_queries.planning_command_resolver import PlanningCommandResolver
from backend.application.services.agent_queries.project_status import ProjectStatusQueryService
from backend.application.services.agent_queries.reporting import ReportingQueryService
from backend.application.services.agent_queries.planning_sessions import (
    PlanningAgentSessionBoardDTO,
    PlanningSessionQueryService,
)
from backend.application.services.agent_queries.workflow_intelligence import WorkflowDiagnosticsQueryService

__all__ = [
    # Cache module and helpers (CACHE-003, P2-001, P2-002, P2-006)
    "cache",
    "_query_cache",
    "aclear_project_cache",
    "clear_cache",
    "clear_project_cache",
    "compute_cache_key",
    "get_cache",
    "get_data_version_fingerprint",
    "init_postgres_cache_backend",
    # DTOs and shared contracts
    "AARReportDTO",
    "AARReviewDTO",
    "AARReviewFlag",
    "AARReviewQueryService",
    "AgentQueryEnvelope",
    "AgentQueryProjectScope",
    "Bottleneck",
    "CostSummary",
    "DocumentRef",
    "FeatureEvidenceSummary",
    "FeatureEvidenceSummaryService",
    "FeatureForensicsDTO",
    "ArtifactIntelligenceQueryService",
    "KeyMetrics",
    # Live metrics (live-agents-count-v1)
    "LiveActiveCountDTO",
    "LiveMetricsQueryService",
    "ProjectStatusDTO",
    "ProjectStatusQueryService",
    "QueryStatus",
    "SessionRef",
    "SessionSummary",
    "SnapshotDiagnosticsDTO",
    "ArtifactRankingsDTO",
    "ArtifactRecommendationsDTO",
    "TaskRef",
    "TimelineData",
    "TurningPoint",
    "WorkflowDiagnostic",
    "WorkflowDiagnosticsDTO",
    "WorkflowDiagnosticsQueryService",
    "FeatureForensicsQueryService",
    "ReportingQueryService",
    "WorkflowObservation",
    "WorkflowSummary",
    "collect_source_refs",
    "derive_data_freshness",
    "normalize_entity_ids",
    "resolve_project_scope",
    "resolve_time_window",
    # Planning query service and DTOs (PCP-201)
    "PlanningQueryService",
    "PlanningCommandCenterQueryService",
    "PlanningCommandResolver",
    "FeaturePlanningContextDTO",
    "FeatureSummaryItem",
    "OpenQuestionResolutionDTO",
    "PhaseContextItem",
    "PhaseOperationsDTO",
    "PhaseTaskItem",
    "PlanningArtifactRef",
    "PlanningCommandAlternativeDTO",
    "PlanningCommandCapabilityDTO",
    "PlanningCommandCenterArtifactDTO",
    "PlanningCommandCenterBlockerDTO",
    "PlanningCommandCenterCapabilitiesDTO",
    "PlanningCommandCenterFeatureDTO",
    "PlanningCommandCenterGitStateDTO",
    "PlanningCommandCenterItemDTO",
    "PlanningCommandCenterLaunchAgentDTO",
    "PlanningCommandCenterLaunchBatchDTO",
    "PlanningCommandCenterPageDTO",
    "PlanningCommandCenterPhaseDTO",
    "PlanningCommandCenterPhaseRowDTO",
    "PlanningCommandCenterPullRequestDTO",
    "PlanningCommandCenterRelatedFileDTO",
    "PlanningCommandCenterStatusDTO",
    "PlanningCommandCenterStoryPointsDTO",
    "PlanningCommandCenterTierDTO",
    "PlanningCommandCenterWorktreeDTO",
    "PlanningCommandResolutionDTO",
    "PlanningCommandRuleId",
    "PlanningCommandTargetArtifactDTO",
    "PlanningNodeCountsByType",
    "PlanningOpenQuestionItem",
    "PlanningSpikeItem",
    "ProjectPlanningSummaryDTO",
    "ProjectPlanningGraphDTO",
    "TokenUsageByModel",
    # Planning session board (PASB-103)
    "PlanningAgentSessionBoardDTO",
    "PlanningSessionQueryService",
    # Next-run preview (PASB-401)
    "NextRunContextRef",
    "PlanningNextRunPreviewDTO",
    "PromptContextSelection",
    # P5a fat-read bundle services and DTOs (T5-001, T5-003, T5-004)
    "AnalyticsBundleQueryService",
    "AnalyticsKPIsDTO",
    "AnalyticsOverviewBundleDTO",
    "AnalyticsTopModelDTO",
    "DashboardBundleDTO",
    "DashboardQueryService",
    "PlanningViewBundleDTO",
    "SessionCardDTO",
]
