import { Project, ProjectTestPlatformConfig } from '../types';
import { ensureProjectTestConfig } from './testConfigDefaults';

const toEnvVar = (platformId: string): string => `${platformId.toUpperCase()}_RESULTS_DIR`;

const quote = (value: string): string => value.replace(/"/g, '\\"');

const platformById = (platforms: ProjectTestPlatformConfig[], id: string): ProjectTestPlatformConfig | null =>
  platforms.find(platform => platform.id === id) || null;

const emitWebDirResolver = (): string[] => [
  'WEB_DIR=""',
  'if [ -d "skillmeat/web" ]; then',
  '  WEB_DIR="skillmeat/web"',
  'elif [ -d "web" ]; then',
  '  WEB_DIR="web"',
  'fi',
  'if [ -z "$WEB_DIR" ]; then',
  '  echo "[warn] No web directory found (expected skillmeat/web or web)."',
  'fi',
  '',
];

export interface GeneratedSetupScript {
  filename: string;
  content: string;
}

export const generateProjectTestSetupScript = (project: Project): GeneratedSetupScript => {
  const cfg = ensureProjectTestConfig(project.testConfig);
  const enabled = cfg.platforms.filter(platform => platform.enabled);
  const lines: string[] = [
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    '',
    '# Generated by CCDash Settings > Projects > Testing',
    `# Project: ${quote(project.name)}`,
    `# Project ID: ${quote(project.id)}`,
    `# Generated: ${new Date().toISOString()}`,
    '',
    'PROJECT_ROOT="${1:-$(pwd)}"',
    'cd "$PROJECT_ROOT"',
    '',
    'echo "[info] Preparing test artifact directories..."',
  ];

  if (enabled.length === 0) {
    lines.push('echo "[warn] No testing platforms are enabled in CCDash settings for this project."');
  }

  for (const platform of enabled) {
    const envName = toEnvVar(platform.id);
    lines.push(`${envName}="${quote(platform.resultsDir || '.')}"`);
    lines.push(`mkdir -p "$${envName}"`);
  }

  lines.push('');
  lines.push('echo "[info] Running configured test commands..."');
  lines.push('');

  const pytest = platformById(enabled, 'pytest');
  if (pytest) {
    lines.push('echo "[run] pytest (JUnit XML)"');
    lines.push(`pytest -v --junitxml "$${toEnvVar('pytest')}/pytest-junit.xml" --cov=skillmeat --cov-report=xml --cov-report=json`);
    lines.push('');
  }

  const coverage = platformById(enabled, 'coverage');
  if (coverage && !pytest) {
    lines.push('echo "[run] coverage capture via pytest"');
    lines.push(`pytest -v --cov=skillmeat --cov-report=xml --cov-report=json --junitxml "$${toEnvVar('coverage')}/pytest-junit.xml"`);
    lines.push('');
  }

  const needsWeb = Boolean(platformById(enabled, 'jest') || platformById(enabled, 'playwright') || platformById(enabled, 'lighthouse'));
  if (needsWeb) {
    lines.push(...emitWebDirResolver());
  }

  const jest = platformById(enabled, 'jest');
  if (jest) {
    lines.push('if [ -n "$WEB_DIR" ]; then');
    lines.push('  echo "[run] jest (JSON + coverage)"');
    lines.push(`  (cd "$WEB_DIR" && pnpm test --json --outputFile "$PROJECT_ROOT/$${toEnvVar('jest')}/jest-results.json")`);
    lines.push('  (cd "$WEB_DIR" && pnpm test:coverage)');
    lines.push('fi');
    lines.push('');
  }

  const playwright = platformById(enabled, 'playwright');
  if (playwright) {
    lines.push('if [ -n "$WEB_DIR" ]; then');
    lines.push('  echo "[run] playwright e2e"');
    lines.push('  (cd "$WEB_DIR" && pnpm test:e2e)');
    lines.push('fi');
    lines.push('');
  }

  const lighthouse = platformById(enabled, 'lighthouse');
  if (lighthouse) {
    lines.push('if [ -n "$WEB_DIR" ]; then');
    lines.push('  echo "[run] lighthouse"');
    lines.push('  (cd "$WEB_DIR" && pnpm test:lighthouse --url http://localhost:3000)');
    lines.push('fi');
    lines.push('');
  }

  const benchmark = platformById(enabled, 'benchmark');
  if (benchmark) {
    lines.push('echo "[run] benchmark suite"');
    lines.push(`python tests/performance/benchmark_api.py --samples 50 --output "$${toEnvVar('benchmark')}/benchmark_api_results.json" --check-server`);
    lines.push(`python tests/performance/benchmark_operations.py --iterations 5 --output "$${toEnvVar('benchmark')}/benchmark_ops_results.json"`);
    lines.push('');
  }

  const locust = platformById(enabled, 'locust');
  if (locust) {
    lines.push('echo "[run] locust load test"');
    lines.push(`locust -f tests/performance/locustfile.py --headless --users 50 --spawn-rate 5 --run-time 3m --host http://localhost:8000 --html "$${toEnvVar('locust')}/locust_report.html" --csv "$${toEnvVar('locust')}/locust_results"`);
    lines.push('');
  }

  const triage = platformById(enabled, 'triage');
  if (triage) {
    lines.push('echo "[run] failure triage parser"');
    lines.push(`python scripts/parse_test_failures.py --input-dir "$${toEnvVar('triage')}" --output "$${toEnvVar('triage')}/test-failures.json" || true`);
    lines.push('');
  }

  lines.push('echo "[done] Test artifact setup and execution complete."');
  lines.push('echo "[next] In CCDash Settings: Validate Paths, then Run Sync Now."');
  lines.push('');

  return {
    filename: `${project.id}-test-setup.sh`,
    content: `${lines.join('\n')}\n`,
  };
};
