"""CCDash contracts — shared Pydantic DTOs for server and CLI."""
from __future__ import annotations

from ccdash_contracts.envelopes import (
    ClientV1Envelope,
    ClientV1ErrorDetail,
    ClientV1ErrorEnvelope,
    ClientV1Meta,
    ClientV1PaginatedEnvelope,
    ClientV1PaginatedMeta,
)
from ccdash_contracts.models import (
    DTOFreshness,
    DocumentRef,
    FeatureCardDTO,
    FeatureCardPageDTO,
    FeatureDependencySummaryDTO,
    FeatureDocumentCoverageDTO,
    FeatureDocumentSummaryDTO,
    FeatureDocumentsDTO,
    FeatureFamilyPositionDTO,
    FeatureModalOverviewDTO,
    FeatureModalSectionDTO,
    FeatureModalSectionItemDTO,
    FeatureModalSectionKey,
    FeatureQualitySignalsDTO,
    FeatureRollupBucketDTO,
    FeatureRollupDTO,
    FeatureRollupErrorDTO,
    FeatureRollupFieldKey,
    FeatureRollupFreshnessDTO,
    FeatureRollupRequestDTO,
    FeatureRollupResponseDTO,
    FeatureSessionsDTO,
    FeatureSummaryDTO,
    FeatureSurfacePrecision,
    InstanceMetaDTO,
    LinkedFeatureSessionDTO,
    LinkedFeatureSessionPageDTO,
    LinkedFeatureSessionTaskDTO,
    LinkedSessionEnrichmentDTO,
    SessionFamilyDTO,
    SessionRef,
)

__all__ = [
    # envelopes
    "ClientV1Envelope",
    "ClientV1ErrorDetail",
    "ClientV1ErrorEnvelope",
    "ClientV1Meta",
    "ClientV1PaginatedEnvelope",
    "ClientV1PaginatedMeta",
    # models
    "DTOFreshness",
    "DocumentRef",
    "FeatureCardDTO",
    "FeatureCardPageDTO",
    "FeatureDependencySummaryDTO",
    "FeatureDocumentCoverageDTO",
    "FeatureDocumentSummaryDTO",
    "FeatureDocumentsDTO",
    "FeatureFamilyPositionDTO",
    "FeatureModalOverviewDTO",
    "FeatureModalSectionDTO",
    "FeatureModalSectionItemDTO",
    "FeatureModalSectionKey",
    "FeatureQualitySignalsDTO",
    "FeatureRollupBucketDTO",
    "FeatureRollupDTO",
    "FeatureRollupErrorDTO",
    "FeatureRollupFieldKey",
    "FeatureRollupFreshnessDTO",
    "FeatureRollupRequestDTO",
    "FeatureRollupResponseDTO",
    "FeatureSessionsDTO",
    "FeatureSummaryDTO",
    "FeatureSurfacePrecision",
    "InstanceMetaDTO",
    "LinkedFeatureSessionDTO",
    "LinkedFeatureSessionPageDTO",
    "LinkedFeatureSessionTaskDTO",
    "LinkedSessionEnrichmentDTO",
    "SessionFamilyDTO",
    "SessionRef",
]
